-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."products" add column "product_qty" integer
--  null default '0';
